title: Weijue Bu's Homepage
page-top-title: Weijue Bu
top-section-bg-text: Computer Science
home-subtitle: Weijue Bu&ensp;|&ensp;卜炜珏
copyright-text: '&copy; Weijue Bu 2024-2025. All Rights Reserved.'
